---
- hosts: all
  vars_files:
    - default.config.yml

  pre_tasks:
    - name: "Include ansible-modules-bitwarden"
      include_role:
        name: ansible-modules-bitwarden
    - name: Load mas email and password
      include_vars:
        mas_email: "{{ lookup('bitwarden', 'Apple ID', field=Username) }}"
        mas_password: "{{ lookup('bitwarden', 'Apple ID', field=Password) }}"
    - debug:
        msg: mas_email
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.dotfiles
  - role: geerlingguy.mac.homebrew
  - role: geerlingguy.mac.mas
    when: mas_installed_apps or mas_installed_app_ids
  - role: geerlingguy.mac.dock
    when: configure_dock
  tasks:
    - include_tasks: ./tasks/configure-sudoers.yml

