---
- hosts: all

  vars_files:
    - defaults.yml
#
#  pre_tasks:
#    - name: Include playbook configuration.
#      include_vars: "{{ item }}"
#      with_fileglob:
#        - "{{ playbook_dir }}/config.yml"
#      tags: ['always']

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.dotfiles
  - role: geerlingguy.mac.homebrew
  - role: geerlingguy.mac.mas
    when: mas_installed_apps or mas_installed_app_ids
  - role: geerlingguy.mac.dock
    when: configure_dock
  tasks:
    - include_tasks: ./tasks/configure-sudoers.yml

