---
- hosts: all
  vars_files:
    - config.yml

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.dotfiles
    tags: ["dotfiles"]
  - role: geerlingguy.mac.homebrew
  tags: ["homebrew"]
  - role: geerlingguy.mac.mas
    when: mas_installed_apps or mas_installed_app_ids
    tags: ["mas"]
  - role: geerlingguy.mac.dock
    tags: ["dock"]
    when: configure_dock
  tasks:
    - include_tasks: ./tasks/configure-sudoers.yml
      tags: ["sudoers"]
    - include_tasks: ./tasks/configure-symlinks.yml
      tags: ["symlinkgs"]
    - include_tasks: ./tasks/install-dmg.yml
      tags: ["dmgs"]
      vars:
        app_name: Goland
        dmg_url: "https://download.jetbrains.com/go/goland-2022.2.2-aarch64.dmg"
