---
name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: "0 5 * * 4"

jobs:

  integration:
    name: Integration
    runs-on: macos-12
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: tests/uninstall-homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs.
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
      - name: Install test dependencies.
        run: sudo pip3 install ansible

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/hosts.ini ./hosts.ini
          # cp tests/config.yml ./config.yml
          
          echo "mas_email: $MAS_EMAIL" >> default.config.yml
          echo "mas_password: $MAS_PASSWORD" >> default.config.yml
          ansible-galaxy install -r requirements.yml
        env:
          MAS_EMAIL: "${{secrets.MAS_EMAIL}}"
          MAS_PASSWORD: "${{secrets.MAS_PASSWORD}}"
      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook main.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook main.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
